### ISSUE TITLE
15주차 PR관련 질문 및 답변 모음

### ISSUE THREAD

**Issue by ScottSung7** [f-lab-edu/check-in-before-leaving#64]

**Comment by ScottSung7** [comment]
1. SearchPlaceService와 KakaoAPIStoreInfoSaver의 유사성. ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/43#discussion_r1740917905))

답변: 
SearchPlaceService는 유저가 어떤 좌표에 위치할때나 특정 단어로 검색을 할 때 특정 범위내의 가게들을 조회해줍니다. 그런데 항상 내부 DB에서 가져오는게 아니다 보니, KakaoAPI에서 조회한 내용을 Redis에 저장을 해주어야 경우가 있는데 이 저장에 관련된 기능을 위임한 클래스가  KakaoAPIStoreInfoSaver입니다. 

처음에는 Redis가 아니라 MySQL에 저장하려고 하다 보니까 아직 둘다 JPA관련 클래스가 남아 있는데 이 부분은 수정 예정입니다. SearchPlaceService에서의 요청이 어쩔 수 없이 저장이라는 사이드 이팩트가 있기는 하지만 저장코드가 들어오기에는 너무 많은 책임이고 클래스도 복잡해 질것 같아서 새로운 클래스인 KakaoAPIStoreInfoSaver를 만들었습니다.

**Comment by ScottSung7** [comment]
2. progress객체를 서비스에서 바로 받을 수 있는지? ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/38#discussion_r1734625520))

답변:
POST API registerProgress()는 등록된 요청을 도와줄 사람(Helper)이 생겼을때 HelperId를 등록시켜주려고 호출을 합니다. 지금은 불완전객체가 생길것 같은 경우에 DTO를 통해서 받고 서비스에서 필요 정보를 모아서 객체를 만들지만, <ins>컨트롤러에서 Form(Request)객체가 가진 인스턴스와 도메인 모델의 인스턴스가 같다면 Progress처럼 바로 변환해서 넘겨줄 수도 있다고 생각했었습니다.</ins> 이런 경우 주의할 점이 있을까요? 어떤 포인트에서 말씀주셨었는지 궁금합니다!

관련이 있는지 모르겠지만 지금은 중간에 DTO가 생겨서 값들로 받고 있지만 원래는 ProgressForm을 받아서 컨트롤러에서 Progress객체로 바꾸어서 서비스로 올려주었었습니다. 

현재: 
<img width="676" alt="Screenshot 2024-09-10 at 11 07 29 AM" src="https://github.com/user-attachments/assets/095113ff-b172-4538-90a0-40d7c0e3e302">

**Comment by ScottSung7** [comment]
3. 빌드와 커밋관련 질문([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/57#pullrequestreview-2288469835))

답변:
Q1. 음.. 그렇군요. 이 부분은 제가 상황에 따라 결정해야 할 부분이겠군요. 너무 세부사항까지 여쭈어 봤던것 같습니다.

Q2. 이 부분은 빌드과정도 docker compose에 넣도록 하겠습니다. ([이슈](https://github.com/f-lab-edu/check-in-before-leaving/pull/57#65))

**Comment by ScottSung7** [comment]
4. return 뒤 띄어쓰기. Formatting문제 ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#discussion_r1749121757))

답변:
그렇군요. 의식적으로 습관을 들이도록 하겠습니다. 일단, Actions on Save설정도 on해 놓았습니다.

**Comment by ScottSung7** [comment]
5. 제네릭에 관련된 문제.([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#discussion_r1749133344))

답변: 
제네릭을 사용하게된 이유는 서비스 코드에서 특정상태를 지정해서 사용하는게 코드 가독성에 좋다고 생각했습니다. 특히, 처음 코드를 읽는 경우에 어떤 서비스에서 어떤 상태(Progress객체)를 사용할지 헷갈릴 수 있다고 생각했습니다. <ins>혹시 아무 타입이나 들어 올수 있어서 염려하시는 걸까요?</ins> Help객체에서 Progress의 자식들만 받도록 한번더 강제를 하고 있기는 한데.. 그래서 Progress의 자식들만 받으니 괜찮다고 생각했습니다.

꼭 제네릭을 가져가고 싶은 것은 아니지만 어떤 부분에서 우려가 될지 알고 싶었습니다.

**Comment by ScottSung7** [comment]
6. Progress 인터페이스에 관한 질문([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#discussion_r1749124832))

답변: 
progress는 help모델의 상태 값으로 들어가기 때문에 비즈니스로직은 없지만 <ins>다형성을 이용하기 위해 사용했습니다.</ins> 진행 상태라는 공통점이 있지만, 인스턴스 필드는 공통점이 적고 이후, 더 적어 질수 있을 것같아서 상속보다는 인터페이스가 좋다고 생각했습니다.

**Comment by ScottSung7** [comment]
7. Help의  Raw use of parameterized class 경고 ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#discussion_r1749134151))

답변: 
A. instanceof 관련 질문: 
HelpJPAReposiotry에서 instanceOf를 통해서 한번 검사를 해주고 있습니다. 원래 체크인, 줄서기, 기타요청 각자 리포지토리를 가졌었지만 

-1. 실 사용시에는 세가지 타입이 각각 요청을 받기 보다는 전체를 모두 조회하는 경우가 일반적일 것같아서 하나씩 조회해서 합쳐주는 것보다 HelpJPARepository로 받는게 좋을 것 같다고 생각했습니다.
-2. 또한, 개별 요청이 적다면 각자 리포지토리를 코드로 만드는건 불필요한 코드를 만드는 것이라고 생각했습니다. 

이렇게 생각하여서 하나의 HelpJPARepository로 변경하였습니다.([관련 파일](https://github.com/f-lab-edu/check-in-before-leaving/blob/10d4de7fc96870c3699daf765b0ca7f910ba2ce7/check-in-request-MS/src/main/java/com/example/checkinrequestMS/HelpAPI/infra/db/help/HelpJPARepository.java))

B. 제네릭 관련 질문: 
Raw use of parameterized class경고가 염려 되기는 하지만 조회시점에 어떤 타입을 받을 지 알수가 없지만 JPA엔티티에서 model엔티티를 내려줄때 getProgress로 알맞은 상태객체를 넣어주고 있기는 합니다. ([관련 파일](https://github.com/f-lab-edu/check-in-before-leaving/blob/10d4de7fc96870c3699daf765b0ca7f910ba2ce7/check-in-request-MS/src/main/java/com/example/checkinrequestMS/HelpAPI/domain/model/help/child/LineUp.java) - LineUpJPAEntity를 받는 2번째 from 입니다.) 

제네릭에 상속까지 사용하다 보니까 복잡해지는것 같습니다. 어떤 방법이 좋을지 다시 여쭈어 봐야 할것 같습니다..

**Comment by ScottSung7** [comment]
8. instance of 패턴 ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#discussion_r1749135386))

답변: 
네.. 아니면 상속 구조를 사용하지 않고 겹치는 부분이 있더라도 각자 객체로 사용하거나 상속을 사용하더라도 각자 리포지토리를 만들어서 사용하는게 좋을까요..?

**Comment by ScottSung7** [comment]
9. 복잡해진 코드 ([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#pullrequestreview-2288470724))

답변([링크](https://github.com/f-lab-edu/check-in-before-leaving/pull/58#issuecomment-2339520621)): 
덜어내는 방향으로 더 고민해 보겠습니다.

처음에 Progress를 값객체로 만드면서 Embedded로 Help에 추가하려고 했는데 이게 또 null값인 필드가 생기다 보니 도메인 계층에 두기에 부담이 되어서 JPA객체와 모델 객체를 나누는 작업까지 진행되다 보니까 작업이 한없이 커져 버렸습니다.. 다음에는 좀 더 Divide & Conquer 해서 나누어서 작업하겠습니다!

여기서 JPA 엔티티와 모델엔티티를 나누었던 리팩토링은 과헀던 걸까요..? 아직 아키텍처적으로 어떻게 접근해야 할지 헷갈리는 점이 많은 것 같습니다.

**Comment by ScottSung7** [comment]
아래는 예전 내용이긴 한데 제가 멘토링때 여쭈어 보지 못했어서 몇개 질문 드립니다.

Q 1: 운영때는 validate나 none을 사용한다고 하는데 보통은 none을 많이 사용한다고 합니다. update, create, create-drop은 데이터 변경가능 하니 절대 안될것 같고, validate는 엔티티와 매핑이 제대로 되어 있으니까 괜찮은거 같은데, 어떤 걸 추천하시나요? ([관련 내용](#21))

**Comment by ScottSung7** [comment]
Q2. 코드에서 중요한 정보를 숨기는 방법에 관련된 질문입니다. 이것도 물어보지 못 했었는데, env파일에 관련된 방법일까요? ([초기 질문](https://github.com/f-lab-edu/check-in-before-leaving/pull/16#discussion_r1697081370)) ([관련 이슈](https://github.com/f-lab-edu/check-in-before-leaving/issues/18#issue-2446270511))

**Comment by heeve1** [comment]
답변을 달은 코멘트는 🎉  이모지를 붙여두었습니다~
