### ISSUE TITLE
FCM 토큰 갱신 방법

### ISSUE THREAD

**Issue by ScottSung7** [f-lab-edu/check-in-before-leaving#97]
현재 최신 토큰을 받을 수 있는지 고려

**Comment by ScottSung7** [comment]
+ 항상 초기화 해야하는지

**Comment by heeve1** [comment]
라이브러리의 객체를 사용할땐 thread safety 를 가장 먼저 확인해보고 그렇다면 빈으로 만들어 쓰는 것이 성능적인 측면에서 좋습니다!
